project_id = "ohwtbkudpkfbakynikyj"

[functions.aggregate-weather]
verify_jwt = true

[functions.fetch-ensemble-forecast]
verify_jwt = false

[functions.ai-weather-insights]
verify_jwt = false

[functions.fetch-hyperlocal-weather]
verify_jwt = false

[functions.fetch-moon-data]
verify_jwt = true

[functions.generate-landmark-image]
verify_jwt = true

[functions.geocode-address]
verify_jwt = false

[functions.find-nearby-stations]
verify_jwt = false

[functions.send-feedback]
verify_jwt = true

[functions.track-analytics]
verify_jwt = false

[functions.verify-predictions]
verify_jwt = true

[functions.process-weather-corrections]
verify_jwt = true

[functions.llm-weather-forecast]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.create-api-subscription]
verify_jwt = true

[functions.report-api-usage]
verify_jwt = false

[functions.generate-api-key]
verify_jwt = true

[functions.clear-analytics]
verify_jwt = true

[functions.populate-analytics]
verify_jwt = true

[functions.create-affiliate-checkout]
verify_jwt = true

[functions.ai-moon-insights]
verify_jwt = false

[functions.notify-blog-post]
verify_jwt = true

[functions.weather-api]
verify_jwt = false

[functions.buy-shop-points]
verify_jwt = false

[functions.confirm-sp-purchase]
verify_jwt = false

[functions.world-weather-average]
verify_jwt = false
